
# cargo-vet config file

[cargo-vet]
version = "0.7"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[imports.zcash.criteria-map]
ours = "crypto-reviewed"
theirs = "crypto-reviewed"

[policy.age]
audit-as-crates-io = false

[policy.age-core]
audit-as-crates-io = false

[policy.age-plugin]
audit-as-crates-io = false

[policy.rage]
audit-as-crates-io = false

[[exemptions.addr2line]]
version = "0.17.0"
criteria = "safe-to-run"

[[exemptions.adler]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.aead]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.aes]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.aes-gcm]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.8.0"
criteria = "safe-to-run"

[[exemptions.aho-corasick]]
version = "0.7.18"
criteria = "safe-to-deploy"

[[exemptions.android-tzdata]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.arc-swap]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.5.3"
criteria = "safe-to-deploy"

[[exemptions.bcrypt-pbkdf]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.bech32]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.block]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.block-padding]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.blowfish]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.bstr]]
version = "0.2.17"
criteria = "safe-to-run"

[[exemptions.bytemuck]]
version = "1.13.1"
criteria = "safe-to-run"

[[exemptions.byteorder]]
version = "1.4.3"
criteria = "safe-to-deploy"

[[exemptions.bzip2]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.bzip2-sys]]
version = "0.1.11+1.0.8"
criteria = "safe-to-deploy"

[[exemptions.cast]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.cbc]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.0.79"
criteria = "safe-to-deploy"

[[exemptions.chacha20]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.chacha20poly1305]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.26"
criteria = "safe-to-deploy"

[[exemptions.cipher]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "2.34.0"
criteria = "safe-to-run"

[[exemptions.clap]]
version = "3.2.25"
criteria = "safe-to-run"

[[exemptions.clap_complete]]
version = "3.2.5"
criteria = "safe-to-run"

[[exemptions.clap_lex]]
version = "0.2.4"
criteria = "safe-to-run"

[[exemptions.console]]
version = "0.15.7"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.9.2"
criteria = "safe-to-deploy"

[[exemptions.constant_time_eq]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.cookie-factory]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.cpp_demangle]]
version = "0.3.5"
criteria = "safe-to-run"

[[exemptions.cpufeatures]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.3.6"
criteria = "safe-to-run"

[[exemptions.criterion-cycles-per-byte]]
version = "0.1.3"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.4.5"
criteria = "safe-to-run"

[[exemptions.crossbeam-channel]]
version = "0.5.7"
criteria = "safe-to-run"

[[exemptions.crossbeam-deque]]
version = "0.8.3"
criteria = "safe-to-run"

[[exemptions.crossbeam-epoch]]
version = "0.9.14"
criteria = "safe-to-run"

[[exemptions.crossbeam-utils]]
version = "0.8.15"
criteria = "safe-to-deploy"

[[exemptions.csv]]
version = "1.1.6"
criteria = "safe-to-run"

[[exemptions.csv-core]]
version = "0.1.10"
criteria = "safe-to-run"

[[exemptions.ctr]]
version = "0.9.2"
criteria = "safe-to-deploy"

[[exemptions.ctrlc]]
version = "3.3.1"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek]]
version = "3.2.0"
criteria = "safe-to-deploy"

[[exemptions.dashmap]]
version = "5.4.0"
criteria = "safe-to-deploy"

[[exemptions.der]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.encode_unicode]]
version = "0.3.6"
criteria = "safe-to-deploy"

[[exemptions.env_logger]]
version = "0.8.4"
criteria = "safe-to-run"

[[exemptions.env_logger]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.filetime]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.find-crate]]
version = "0.6.3"
criteria = "safe-to-deploy"

[[exemptions.findshlibs]]
version = "0.10.2"
criteria = "safe-to-run"

[[exemptions.flate2]]
version = "1.0.26"
criteria = "safe-to-deploy"

[[exemptions.fuse_mt]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.fuser]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.futures]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.futures-macro]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.25"
criteria = "safe-to-deploy"

[[exemptions.futures-test]]
version = "0.3.28"
criteria = "safe-to-run"

[[exemptions.futures-util]]
version = "0.3.21"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.6"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.1.16"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.10"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.26.1"
criteria = "safe-to-run"

[[exemptions.gumdrop]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.gumdrop_derive]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.1.19"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.hkdf]]
version = "0.12.3"
criteria = "safe-to-deploy"

[[exemptions.hmac]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.i18n-config]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.i18n-embed]]
version = "0.13.8"
criteria = "safe-to-deploy"

[[exemptions.i18n-embed-fl]]
version = "0.6.7"
criteria = "safe-to-deploy"

[[exemptions.i18n-embed-impl]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone]]
version = "0.1.57"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone-haiku]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "1.9.1"
criteria = "safe-to-run"

[[exemptions.inferno]]
version = "0.11.14"
criteria = "safe-to-run"

[[exemptions.instant]]
version = "0.1.12"
criteria = "safe-to-deploy"

[[exemptions.io-lifetimes]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.io_tee]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.10.5"
criteria = "safe-to-run"

[[exemptions.itoa]]
version = "0.4.8"
criteria = "safe-to-run"

[[exemptions.itoa]]
version = "1.0.6"
criteria = "safe-to-deploy"

[[exemptions.jobserver]]
version = "0.1.26"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.63"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.146"
criteria = "safe-to-deploy"

[[exemptions.libm]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.3.8"
criteria = "safe-to-deploy"

[[exemptions.locale_config]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.10"
criteria = "safe-to-deploy"

[[exemptions.man]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.memchr]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.memmap2]]
version = "0.5.10"
criteria = "safe-to-run"

[[exemptions.memoffset]]
version = "0.6.5"
criteria = "safe-to-run"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.5.3"
criteria = "safe-to-run"

[[exemptions.miniz_oxide]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.nix]]
version = "0.24.3"
criteria = "safe-to-run"

[[exemptions.nix]]
version = "0.26.1"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "7.1.1"
criteria = "safe-to-deploy"

[[exemptions.num-bigint-dig]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.num-format]]
version = "0.4.4"
criteria = "safe-to-run"

[[exemptions.num_cpus]]
version = "1.13.1"
criteria = "safe-to-deploy"

[[exemptions.num_threads]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.objc]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.objc-foundation]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.objc_id]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.30.4"
criteria = "safe-to-run"

[[exemptions.once_cell]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.oorandom]]
version = "11.1.3"
criteria = "safe-to-run"

[[exemptions.os_str_bytes]]
version = "6.5.1"
criteria = "safe-to-run"

[[exemptions.page_size]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.password-hash]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.pbkdf2]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.percent-encoding]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.pinentry]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.pkcs1]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.pkcs8]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.27"
criteria = "safe-to-deploy"

[[exemptions.plotters]]
version = "0.3.4"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.4"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.3"
criteria = "safe-to-run"

[[exemptions.poly1305]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.polyval]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.pprof]]
version = "0.10.1"
criteria = "safe-to-run"

[[exemptions.ppv-lite86]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error-attr]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.60"
criteria = "safe-to-deploy"

[[exemptions.quick-xml]]
version = "0.26.0"
criteria = "safe-to-run"

[[exemptions.quickcheck]]
version = "1.0.3"
criteria = "safe-to-run"

[[exemptions.rand]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.rand_hc]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.5.6"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.1.10"
criteria = "safe-to-run"

[[exemptions.regex-syntax]]
version = "0.6.26"
criteria = "safe-to-deploy"

[[exemptions.rgb]]
version = "0.8.36"
criteria = "safe-to-run"

[[exemptions.roff]]
version = "0.1.0"
criteria = "safe-to-run"

[[exemptions.rpassword]]
version = "6.0.1"
criteria = "safe-to-deploy"

[[exemptions.rsa]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.rust-embed]]
version = "6.7.0"
criteria = "safe-to-deploy"

[[exemptions.rust-embed-impl]]
version = "6.6.0"
criteria = "safe-to-deploy"

[[exemptions.rust-embed-utils]]
version = "7.5.0"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "0.37.20"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.13"
criteria = "safe-to-deploy"

[[exemptions.salsa20]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.same-file]]
version = "1.0.6"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.scrypt]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.secrecy]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.self_cell]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.164"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.164"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.81"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.signature]]
version = "1.6.4"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.10.0"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.spki]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.stable_deref_trait]]
version = "1.2.0"
criteria = "safe-to-run"

[[exemptions.static_assertions]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.str_stack]]
version = "0.1.0"
criteria = "safe-to-run"

[[exemptions.strsim]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.subtle]]
version = "2.4.1"
criteria = "safe-to-deploy"

[[exemptions.symbolic-common]]
version = "9.2.1"
criteria = "safe-to-run"

[[exemptions.symbolic-demangle]]
version = "9.2.1"
criteria = "safe-to-run"

[[exemptions.syn]]
version = "1.0.109"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.18"
criteria = "safe-to-deploy"

[[exemptions.tar]]
version = "0.4.38"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.6.0"
criteria = "safe-to-deploy"

[[exemptions.termcolor]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.test-case]]
version = "2.2.2"
criteria = "safe-to-run"

[[exemptions.test-case-macros]]
version = "2.2.2"
criteria = "safe-to-run"

[[exemptions.textwrap]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.textwrap]]
version = "0.16.0"
criteria = "safe-to-run"

[[exemptions.threadpool]]
version = "1.8.1"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.1.44"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.15"
criteria = "safe-to-deploy"

[[exemptions.tinytemplate]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.tokio]]
version = "1.28.2"
criteria = "safe-to-run"

[[exemptions.tokio-macros]]
version = "2.1.0"
criteria = "safe-to-run"

[[exemptions.toml]]
version = "0.5.9"
criteria = "safe-to-deploy"

[[exemptions.type-map]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.users]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.uuid]]
version = "1.3.3"
criteria = "safe-to-run"

[[exemptions.version_check]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.walkdir]]
version = "2.3.3"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.9.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.10.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.86"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.86"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.86"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.86"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.86"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.63"
criteria = "safe-to-deploy"

[[exemptions.which]]
version = "4.3.0"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows]]
version = "0.48.0"
criteria = "safe-to-deploy"

[[exemptions.wsl]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.x25519-dalek]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.xattr]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.5.7"
criteria = "safe-to-deploy"

[[exemptions.zeroize_derive]]
version = "1.3.2"
criteria = "safe-to-deploy"

[[exemptions.zip]]
version = "0.6.6"
criteria = "safe-to-deploy"

[[exemptions.zstd]]
version = "0.11.2+zstd.1.5.2"
criteria = "safe-to-deploy"

[[exemptions.zstd-safe]]
version = "5.0.2+zstd.1.5.2"
criteria = "safe-to-deploy"

[[exemptions.zstd-sys]]
version = "2.0.4+zstd.1.5.2"
criteria = "safe-to-deploy"
